### ISSUE TITLE
Handler onUserSelClose not found

### ISSUE THREAD

**Issue by scop** [davesteele/gnome-gmail#31]
Relaying issue here, I have not experienced it myself:

https://bugzilla.redhat.com/show_bug.cgi?id=1264237
https://bugzilla.redhat.com/show_bug.cgi?id=1316217

```
Gtk.py:83:_extract_handler_and_args:AttributeError: Handler onUserSelClose not found

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler onUserSelClose not found

Local variables in innermost frame:
obj_or_map: <__main__.do_preferred.<locals>.Handler object at 0xb4c0f12c>
handler: None
handler_name: 'onUserSelClose'
```

**Comment by davesteele** [comment]
Python 3 has other problems as well (#29). I may need to make it explicitly python2 for a while.
