### ISSUE TITLE
Crash on start / Need to give permission

### ISSUE THREAD

**Issue by FFortissimo** [davesteele/gnome-gmail#51]
New system (2 months now).
Fedora 25
Chrome 57.0.2987.133 (64-bit)
Gnome 3 (Wayland)

Fresh install and after removal en reinstall and updates, this problem still exists.

Clicking on an e-maillink gives a pop-up asking for permission.
At the same time I get a message from Gnome that gnome-gmail has crashed and a report has been send.

Runned from the command-line:
Traceback (most recent call last):
  File "/usr/share/gnome-gmail/gnomegmail.py", line 852, in <module>
    main()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 837, in main
    gmailurl = gm_url.gmail_url()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 563, in gmail_url
    gmailurl = self.api_gmail_url()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 541, in api_gmail_url
    self.from_address):
  File "/usr/share/gnome-gmail/gnomegmail.py", line 291, in access_iter
    yield self.generate_tokens(login)
  File "/usr/share/gnome-gmail/gnomegmail.py", line 274, in generate_tokens
    code = self.get_code(login)
  File "/usr/share/gnome-gmail/gnomegmail.py", line 211, in get_code
    screen.force_update()
AttributeError: 'NoneType' object has no attribute 'force_update'

less ~/.config/gnome-gmail/gnome-gmail.conf
[gnome-gmail]
suppress_preferred = 0
last_email = xxx
browser_options = 
suppress_account_selection = 1
new_browser = 1

I checked older messages but the solutions didn't work/were already installed.

**Comment by davesteele** [comment]
I don't have access to a Fedora installation. Someone with that environment will need to run it to ground.

The lifetime of the 'screen' object up to the point of the crash is essentially as follows:

gi.require_version('Wnck', '3.0')
from gi.repository import Wnck
screen = Wnck.Screen.get_default()
screen.force_update()

**Comment by FFortissimo** [comment]
To be honest, I don't know what you wrote ;)
I hope a fellow Fedora user can shed some light on it.

**Comment by davesteele** [comment]
I was using maintainer speak, for the guy who may fix this.

**Comment by davesteele** [comment]
The Fedora bug list for gnome-gmail can be accessed [here](https://apps.fedoraproject.org/packages/gnome-gmail/bugs)
