### ISSUE TITLE
FileNotFoundError: ~/.kde/share/config/emaildefaults

### ISSUE THREAD

**Issue by sevku** [davesteele/gnome-gmail#78]
```
$ gnome-gmail
Traceback (most recent call last):
  File "/usr/share/gnome-gmail/gnomegmail.py", line 1009, in <module>
    main()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 969, in main
    if not is_default_mailer() \
  File "/usr/share/gnome-gmail/gnomegmail.py", line 133, in is_default_mailer
    with open(cfgpath, 'r') as cfp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.kde/share/config/emaildefaults'
```

**Comment by davesteele** [comment]
KDE support is broken. See #30.

**Comment by sevku** [comment]
> KDE support is broken. See #30.

Why exactly has there been no progress on this?

**Comment by davesteele** [comment]
There has been no progress because no one has worked on it.

If the goal is to have it work with KDE, than it needs to be debugged by someone running that environment. This has not been a significant goal for me.

**Comment by sevku** [comment]
I've actually fixed that bug I think. But I'm running into an other one which I'm clueless about now:

```
$ python gnomegmail.py 
gnomegmail.py:607: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  SafeConfigParser.__init__(self, *args, **kwargs)
Traceback (most recent call last):
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler onUserSelClose not found
Traceback (most recent call last):
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler onDestroy not found
Traceback (most recent call last):
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler onDestroy not found
Traceback (most recent call last):
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/home/user/tmp/scop-gnome-gmail/venv/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler onOkClicked not found
```

**Comment by davesteele** [comment]
It appears to be from [this](https://github.com/davesteele/gnome-gmail/blob/1d99a4464edc410e9ebfc87ef38806b8731575be/gnomegmail.py#L655). Why, I don't know.

**Comment by sevku** [comment]
Does it have to be run with Python 2.7? Or can it be run with python 3.x?

**Comment by davesteele** [comment]
It was first developed with 2.7, but I make no guarantees that it is still compatible. It is EOL.

**Comment by sevku** [comment]
@davesteele I've been looking into this a little more and I've got some questions and issues

The questtion is, how should it behave when entering an email?
In my case, it literally just opens a browser with gmail.com,  entering an email in the popup has no effect, it loads whatever account is currently logged in in that browser.

The other thing is that setting default email application doesn't yet work on KDE, but I will fix that if I get to it, just wanted to note that down here.

**Comment by davesteele** [comment]
That could be a bug. If there is an email being generated, the URL given by the GMail API should specify the correct user. But, in the case where you are just opening up the browser, that logic is not in place. Not something I test extensively.
