### ISSUE TITLE
Error using gnome-gmail on Ubuntu 20.04

### ISSUE THREAD

**Issue by aldolovlc** [davesteele/gnome-gmail#85]
After geting the permission token, every time I try to send a mail using
```
gnome-gmail example@example.com
```
The browser opens the gmail drafts page, but without any form to write the message.

And if I try to send a file using
```
gnome-gmail -r file.txt
```
Python drops this error message:
```
Traceback (most recent call last):
  File "./gnomegmail.py", line 1009, in <module>
    main()
  File "./gnomegmail.py", line 983, in main
    from_address = fromFromMessage(message)
  File "./gnomegmail.py", line 718, in fromFromMessage
    line = [x for x in message.split('\n') if 'FROM:' in x.upper()][0]
IndexError: list index out of range
```

**Comment by davesteele** [comment]
As far as the second failure goes, the Gmail API requires a valid To address. I'm not currently running an environment where I can evaluate the first.

gnome-gmail mailto:example@example.com?attach=file.txt
